# Generated by Django 5.2.7 on 2025-10-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('temperamento', models.CharField(max_length=255)),
                ('esperanza_vida', models.CharField(max_length=50)),
                ('descripcion_completa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='favoriteCat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cat')),
            ],
        ),
    ]
