# Generated by Django 5.2.7 on 2025-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_favoritecat_cat_favoritecat_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecat',
            name='breed_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='favoritecat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
