# Generated by Django 5.2.7 on 2025-10-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_favoritecat_breed_id_alter_favoritecat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecat',
            name='breed_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
